---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 1Gi } }
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-pvc
spec:
  containers:
  - image: alpine
    command:
      - sleep
      - "36000"
    imagePullPolicy: IfNotPresent
    name: alpine
    volumeMounts:
      - name: pvc
        mountPath: /mnt/pvc
  restartPolicy: Always
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: test-pvc
