apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
  - image: alpine
    command:
      - sleep
      - "36000"
    imagePullPolicy: IfNotPresent
    name: alpine
  restartPolicy: Always
