apiVersion: v1
kind: Pod
metadata:
  name: another-nginx-with-svc
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: http-web-svc
    volumeMounts:
      - name: config-volume1
        mountPath: /usr/share/nginx/html
  volumes:
  - name: config-volume1
    configMap:
      name: nginx-m1
